---
version: "2.1"
services:
  bolsas-scraper:
    image: rafaelsgirao/bolsas-scraper:v1.0.0
    container_name: bolsas-scraper
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
